=== danicastillo96/ifcd0210/Cliente/UF1841/E2/XML_DTD_XSD/sistemasolar.dtd
<!ELEMENT sistemasolar (cuerpos, satelite)+>
<!ELEMENT cuerpos (planeta)>
<!ELEMENT planeta (#PCDATA)>
<!ELEMENT satelite (luna)>
<!ELEMENT luna (#PCDATA)>

=== danicastillo96/ifcd0210/Cliente/UF1841/E2/XML_DTD_XSD/sistemasolar.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sistemasolar SYSTEM "sistemasolar.dtd">


<sistemasolar xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="sistemasolar.xsd">
	<cuerpos>
		<planeta>Mercurio</planeta>
	</cuerpos>
	<satelite>
	<luna>NO</luna>
	</satelite>
	<cuerpos>
		<planeta>Venus</planeta>
	</cuerpos>
	<satelite>
	<luna>NO</luna>
	</satelite>
	<cuerpos>
		<planeta>Tierra</planeta>
	</cuerpos>
	<satelite>
	<luna>SI</luna>
	</satelite>
	<cuerpos>
		<planeta>Marte</planeta>
	</cuerpos>
	<satelite>
		<luna>NO</luna>
	</satelite>
	<cuerpos>
		<planeta>Júpiter</planeta>
	</cuerpos>
	<satelite>
		<luna>SI</luna>
	</satelite>
		<cuerpos>
		<planeta>Saturno</planeta>
	</cuerpos>
	<satelite>
		<luna>SI</luna>
	</satelite>
	<cuerpos>
		<planeta>Urano</planeta>
	</cuerpos>
	<satelite>
		<luna>SI</luna>
	</satelite>
	<cuerpos>
		<planeta>Neptuno</planeta>
	</cuerpos>
	<satelite>
		<luna>SI</luna>
	</satelite>
</sistemasolar>
